### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by bboalimoe** [ngineered/nginx-nodejs#1]
can this docker container be used in production environment..
do we need to start more than one instance of node
thanks a lot~

**Comment by richarvey** [comment]
You could use this in production yes. If you want high availability I'd
recommend more than one host and multiple containers. If you want some
architecture help just mail me on ric@ngineered.co.uk.

*Richard Harvey*
*~~~~~~~~~~~*
Ngineered Ltd.
*web:* http://ngineered.co.uk
*twitter: *@ngineered <https://twitter.com/ngineered>
*tel:* 0800 088 5823
*mob:* 07798 656 019

**Comment by bboalimoe** [comment]
ok~ thanks a lot~
